In [265]:
using LinearAlgebra

In [266]:
A = [
    -1 0 1 1/2
    1/3 -1 0 0
    1/3 1/2 -1 1/2
    1/3 1/2 0 -1
    1 1 1 1
]

5×4 Matrix{Float64}:
 -1.0        0.0   1.0   0.5
  0.333333  -1.0   0.0   0.0
  0.333333   0.5  -1.0   0.5
  0.333333   0.5   0.0  -1.0
  1.0        1.0   1.0   1.0

In [267]:
b = [zeros(4);1]

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 1.0

In [268]:
importancia = A \ b

4-element Vector{Float64}:
 0.3870967741935485
 0.12903225806451604
 0.29032258064516125
 0.19354838709677422

In [269]:
norm(A*importancia-b)

1.716587549445839e-16

In [270]:
🐱 = [
    0 0 1 1/2
    1/3 0 0 0
    1/3 1/2 0 1/2
    1/3 1/2 0 0
]

4×4 Matrix{Float64}:
 0.0       0.0  1.0  0.5
 0.333333  0.0  0.0  0.0
 0.333333  0.5  0.0  0.5
 0.333333  0.5  0.0  0.0

In [271]:
function simulacao(vetor, min)
    for i=1:min
        vetor = 🐱*vetor
    end
    return vetor
    
end

simulacao (generic function with 1 method)

In [272]:
vetor = 25*ones(4)

4-element Vector{Float64}:
 25.0
 25.0
 25.0
 25.0

In [273]:
final = simulacao(vetor, 6000)

4-element Vector{Float64}:
 38.70967741935479
 12.903225806451596
 29.032258064516093
 19.354838709677395

In [274]:
sum(final)

99.99999999999987

In [275]:
eigen(🐱)

Eigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
values:
4-element Vector{ComplexF64}:
 -0.36062333350611053 - 0.4109755454950538im
 -0.36062333350611053 + 0.4109755454950538im
   -0.278753332987779 + 0.0im
    1.000000000000002 + 0.0im
vectors:
4×4 Matrix{ComplexF64}:
 -0.755216-0.0im        …   0.506486+0.0im   0.72101+0.0im
  0.303672-0.346072im      -0.605656+0.0im  0.240337+0.0im
 0.0931532+0.274678im      -0.381539+0.0im  0.540758+0.0im
   0.35839+0.0713946im      0.480709+0.0im  0.360505+0.0im

In [276]:
🐱 = randn(2,2)
v=[100,2030]

2-element Vector{Int64}:
  100
 2030

In [277]:
simulacao(v, 1000)

2-element Vector{Float64}:
 -9.69202991022629e71
 -9.272672214625707e71