In [87]:
function divide_por_2(x)
    metade=convert(Int, length(x)/2)
    return x[1:metade], x[metade+1:end]
end

divide_por_2 (generic function with 1 method)

In [88]:
function F(c)
   n = length(c)
   if n == 1
    return c
   else
    c1, c2 = divide_por_2(c)

    y1antigo = F(c1)/sqrt(2)
    y2antigo = F(c2)/sqrt(2)

    y1 = y1antigo + y2antigo
    y2 = y1antigo - y2antigo
    y = [y1;y2]

    return y
   end
end

F (generic function with 1 method)

In [89]:
c = randn(8,1)

8×1 Matrix{Float64}:
 -0.8342176437246996
  0.001690322683677479
 -2.5112001432745634
  0.7729658290997795
  0.5082398139464619
 -0.9449787369654966
  1.3636318130546046
  2.6936899560958687

In [90]:
F(c)

8-element Vector{Float64}:
  0.3711678486359584
 -1.41312233076208
 -1.2686746169420038
  1.8496268311627935
 -2.188970833711272
 -1.5002098903411487
  1.9091061735549644
 -0.11844699305000472

In [91]:
primeiracoluna = zeros(8)
primeiracoluna[1]=1
primeiracoluna

8-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [92]:
F(primeiracoluna)

8-element Vector{Float64}:
 0.3535533905932737
 0.3535533905932737
 0.3535533905932737
 0.3535533905932737
 0.3535533905932737
 0.3535533905932737
 0.3535533905932737
 0.3535533905932737

In [93]:
# Inicializa a matriz
matriz = zeros(8, 8)

# Preenche cada coluna da matriz
for i in 1:8
    coluna = zeros(8)
    coluna[i] = 1
    resultado = F(coluna)
    matriz[:, i] = resultado

end

matriz

8×8 Matrix{Float64}:
 0.353553   0.353553   0.353553  …   0.353553   0.353553   0.353553
 0.353553  -0.353553   0.353553     -0.353553   0.353553  -0.353553
 0.353553   0.353553  -0.353553      0.353553  -0.353553  -0.353553
 0.353553  -0.353553  -0.353553     -0.353553  -0.353553   0.353553
 0.353553   0.353553   0.353553     -0.353553  -0.353553  -0.353553
 0.353553  -0.353553   0.353553  …   0.353553  -0.353553   0.353553
 0.353553   0.353553  -0.353553     -0.353553   0.353553   0.353553
 0.353553  -0.353553  -0.353553      0.353553   0.353553  -0.353553

$$0.353553 ≈ 1/\sqrt{8} = (1/\sqrt{2})^3$$

In [94]:
matriz*matriz'

8×8 Matrix{Float64}:
 1.0          5.90395e-18  5.90395e-18  …  2.18516e-17  5.90395e-18
 5.90395e-18  1.0          7.97384e-18     5.90395e-18  2.18516e-17
 5.90395e-18  7.97384e-18  1.0             5.90395e-18  7.97384e-18
 7.97384e-18  5.90395e-18  5.90395e-18     7.97384e-18  5.90395e-18
 5.90395e-18  7.97384e-18  2.18516e-17     5.90395e-18  7.97384e-18
 7.97384e-18  5.90395e-18  5.90395e-18  …  7.97384e-18  5.90395e-18
 2.18516e-17  5.90395e-18  5.90395e-18     1.0          5.90395e-18
 5.90395e-18  2.18516e-17  7.97384e-18     5.90395e-18  1.0